version: '3.8'

services:
  planner:
    build:
      context: .
      dockerfile: services/planner/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rodex
      - REDIS_URL=redis://redis:6379
      - AUTOMATION_URL=http://automation:8081
    depends_on:
      - postgres
      - redis
  
  automation:
    build:
      context: .
      dockerfile: services/automation/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rodex
      - REDIS_URL=redis://redis:6379
      - PLANNER_URL=http://planner:8080
      - PLAYWRIGHT_BROWSERS_PATH=/data/browsers
    volumes:
      - playwright-data:/data
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rodex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  playwright-data:
