[build]
builder = "NIXPACKS"
buildCommand = """
pip install -e ../../.[automation] && \
npx playwright install-deps && \
npx playwright install chromium
"""

[deploy]
startCommand = "python -m services.automation.main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[volumes]]
name = "playwright-cache"
mountPath = "/data"

[deploy.healthcheck]
path = "/health"
timeout = 100
interval = 10
