[build]
builder = "NIXPACKS"
buildCommand = "pip install -e ../../.[planner]"

[deploy]
startCommand = "uvicorn services.planner.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
timeout = 100
interval = 10
